//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом_Альбион
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Товар_Заказ = new HashSet<Товар_Заказ>();
        }
    
        public int ID_Заказа { get; set; }
        public int ID_Клиента { get; set; }
        public int ID_Сотрудника { get; set; }
        public System.DateTime ДатаОформления { get; set; }
        public decimal Сумма { get; set; }
        public int ID_Статуса { get; set; }
        public int ID_ВидаЗаказа { get; set; }
        public bool Уведомление { get; set; }
        public Nullable<System.DateTime> ДатаВыполнения { get; set; }
        public bool Доставка { get; set; }
    
        public virtual Виды_заказов Виды_заказов { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Статус Статус { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товар_Заказ> Товар_Заказ { get; set; }
    }
}
