//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом_Альбион
{
    using System;
    using System.Collections.Generic;
    
    public partial class Персональные_данные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Персональные_данные()
        {
            this.Клиенты = new HashSet<Клиенты>();
            this.Сотрудники = new HashSet<Сотрудники>();
        }
    
        public int ID_ПерсДанных { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Серия { get; set; }
        public string Номер { get; set; }
        public string Отчество { get; set; }
        public string Эл_почта { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> ID_Пользователя { get; set; }
        public int ID_Роли { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Клиенты> Клиенты { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Роли Роли { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
    }
}
