//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом_Альбион
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Товар_Заказ = new HashSet<Товар_Заказ>();
        }
    
        public int ID_Товара { get; set; }
        public string Название { get; set; }
        public decimal Цена { get; set; }
        public Nullable<int> ID_Производителя { get; set; }
        public Nullable<int> ID_Категории { get; set; }
        public string Описание { get; set; }
    
        public virtual Категории Категории { get; set; }
        public virtual Производитель Производитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товар_Заказ> Товар_Заказ { get; set; }
    }
}
